### ISSUE TITLE
Repository Integration

### ISSUE THREAD

**Issue by NeroCube** [kkbruce/reverse-interview-zh-Hant#1]
Welcome to send PR in [Traditional Chinese version](https://github.com/NeroCube/reverse-interview-zh-tw)

**Comment by kkbruce** [comment]
@NeroCube 

如果 https://github.com/NeroCube/reverse-interview-zh-tw/commit/7a32d9bf0b9e81da0b486ed047193dbe2d315226 這樣的複製貼上就是你所謂的 PR，這相當令人不屑。請移除從我這裡複製的翻譯，重新Fork去修改。

在我的原文已經說明的很清楚了。你自己不持續更新，只想等著別人提PR，我想自己練功，不代表我要PR給你，不代表你可以直接"**複製貼上**"**我的翻譯內容**，並當成自己帶的作品。我們都是有放上CC授權條款，看來你只是放好看的，完全不懂「姓名標示」是什麼意思。再說一次，請移除從我這裡複製的翻譯，重新Fork去修改，採用符合「CC授權條款」對你對我才是好的方式。

**Comment by NeroCube** [comment]
@kkbruce 
You can git diff the commit.You will find my version is different from yours.Why do you think I copied content from your repo?This issue is just advice not a request.Thanks for your contribution on open source.

**Comment by kkbruce** [comment]
@NeroCube 
是的，我錯了。經過我人工比對後，只能說非常高度相似，所以不能說是你的問題。反正英文人人都能翻，尤其是這種短短的句子，翻出來長得一模一樣也沒有什麼好大驚小怪的。
